version: "3.3"
services:

  chat-service:
    build: 
      context: .
    image: node:16-alpine
    env_file: docker-compose.env
    container_name: chat-service
    depends_on:
      - chat-db
    networks:
      - internal

  chat-db:
    image: mongo:latest
    container_name: chat-db
    ports:
      - 5100:27017
    networks:
      - internal

networks:
  internal:

volumes:
  data:
