version: "3.3"
services:
  mailer-service:
    build: 
      context: .
    image: node:16-alpine
    env_file: docker-compose.env
    container_name: mailer-service
    depends_on:
      - mailer-db
    networks:
      - internal

networks:
  internal:

volumes:
  data:
