name: Api gateway service integration
on:
  pull_request:
    branches: [main]

jobs:
  test_api_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          cd ./api
          npm ci
          npm test
